assets/convert_cards_to_png.sh
@Yamaguti Can you please test if this works?
=> [feat] add inkscape 0.x compatibility

src/main/java/br/com/sbk/sbking/gui/frames/CagandoNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/KingNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/MinibridgeClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/NetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/PositiveKingNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/listeners/ClientActionListener.java, src/main/java/br/com/sbk/sbking/gui/main/ClientApplicationState.java, src/main/java/br/com/sbk/sbking/gui/main/MainNetworkGame.java, src/main/java/br/com/sbk/sbking/gui/painters/DealPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/DealWithDummyPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/SpectatorPainter.java, src/main/java/br/com/sbk/sbking/logging/SBKingLogger.java, src/main/java/br/com/sbk/sbking/networking/client/ClientToServerMessageSender.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/core/properties/FileProperties.java, src/main/java/br/com/sbk/sbking/networking/core/serialization/Serializator.java, src/main/java/br/com/sbk/sbking/networking/server/CagandoNoBequinhoGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/ClientGameSocket.java, src/main/java/br/com/sbk/sbking/networking/server/GameServer.java, src/main/java/br/com/sbk/sbking/networking/server/KingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/LobbyServer.java, src/main/java/br/com/sbk/sbking/networking/server/MessageSender.java, src/main/java/br/com/sbk/sbking/networking/server/MinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/PositiveKingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java, src/main/java/br/com/sbk/sbking/networking/server/main/LobbyServerStarter.java
I figured a Singleton would not be necessary, as a public static field is ok. Please comment if you think that is very ugly or problematic.
=> [refactor] unique call to getLogger on project

src/main/java/br/com/sbk/sbking/networking/core/serialization/Serializator.java, src/main/java/br/com/sbk/sbking/networking/server/ClientGameSocket.java, src/main/java/br/com/sbk/sbking/networking/server/MessageSender.java, src/main/java/br/com/sbk/sbking/networking/server/PlayerNetworkInformation.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java
Unfortunately, the threads themselves are not being TERMINATED but only
PARKED as we are not escalating enough to call its shutdown. Anyway,
this should not be a problem if the important resources (sockets) are
released.
=> [feat] disconnect gracefully and release resources

src/main/java/br/com/sbk/sbking/gui/listeners/ClientActionListener.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/messages/MessageConstants.java, src/main/java/br/com/sbk/sbking/networking/server/ClientGameSocket.java
Please merge [PR 48](https://github.com/rulojuka/sbking/pull/48) before evaluating this one.
=> [fix] stability fix. Client pings server to keep connection from closing

src/main/java/br/com/sbk/sbking/core/Board.java, src/main/java/br/com/sbk/sbking/core/Card.java, src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/core/GameModeSummary.java, src/main/java/br/com/sbk/sbking/core/Hand.java, src/main/java/br/com/sbk/sbking/core/Player.java, src/main/java/br/com/sbk/sbking/core/Score.java, src/main/java/br/com/sbk/sbking/core/Trick.java, src/main/java/br/com/sbk/sbking/core/rulesets/abstractClasses/NegativeRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/abstractClasses/PositiveRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/abstractClasses/Ruleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeHeartsRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeKingRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeLastTwoRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeMenRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeTricksRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NegativeWomenRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/NoRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/PositiveNoTrumpsRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/concrete/PositiveWithTrumpsRuleset.java, src/main/java/br/com/sbk/sbking/core/rulesets/implementations/DefaultSuitFollowable.java, src/main/java/br/com/sbk/sbking/core/rulesets/implementations/DontProhibitsHearts.java, src/main/java/br/com/sbk/sbking/core/rulesets/implementations/NoTrumpSuitWinnable.java, src/main/java/br/com/sbk/sbking/core/rulesets/implementations/ProhibitsHearts.java, src/main/java/br/com/sbk/sbking/core/rulesets/implementations/TrumpSuitWinnable.java, src/main/java/br/com/sbk/sbking/gui/constants/FrameConstants.java, src/main/java/br/com/sbk/sbking/gui/models/KingGameScoreboard.java
=> [refactor] remove unnecessary Serializable implementations

src/main/java/br/com/sbk/sbking/networking/kryonet/ConnectionWithIdentifier.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java
=> [fix] avoid ConcurrentModificationException on KryonetSBKingServer

src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClientFactory.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetClientFactory.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetClientListenerFactory.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetServerListenerFactory.java, src/main/java/br/com/sbk/sbking/networking/kryonet/ReconnectToServerRunner.java
=> [feat] try to reconnect after each disconnection.

src/main/java/br/com/sbk/sbking/core/CagandoNoBequinhoGame.java, src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/core/KingGame.java, src/main/java/br/com/sbk/sbking/core/MinibridgeGame.java, src/main/java/br/com/sbk/sbking/core/PositiveKingGame.java, src/main/java/br/com/sbk/sbking/core/TrickGame.java, src/main/java/br/com/sbk/sbking/gui/main/MainNetworkGame.java, src/main/java/br/com/sbk/sbking/gui/painters/DealPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/SpectatorPainter.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingClientMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/server/LobbyServer.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/KingGameServer.java, src/test/java/br/com/sbk/sbking/core/CagandoNoBequinhoGameTest.java, src/test/java/br/com/sbk/sbking/core/DealTest.java, src/test/java/br/com/sbk/sbking/core/KingGameTest.java, src/test/java/br/com/sbk/sbking/core/MinibridgeGameTest.java, src/test/java/br/com/sbk/sbking/core/PositiveKingGameTest.java
=> [fix] all game servers

src/main/java/br/com/sbk/sbking/gui/frames/CagandoNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/KingNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/MinibridgeClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/NetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/frames/PositiveKingNetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/main/MainNetworkGame.java, src/main/java/br/com/sbk/sbking/networking/server/LobbyServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/CagandoNoBequinhoGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/GameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/KingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/MinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/PositiveKingGameServer.java
=> Refactoring game servers

gitignore_example, pom-client.xml, pom.xml, src/main/java/br/com/sbk/sbking/core/constants/ErrorCodes.java, src/main/java/br/com/sbk/sbking/gui/JElements/ConnectToServerButton.java, src/main/java/br/com/sbk/sbking/gui/elements/ConnectToServerElement.java, src/main/java/br/com/sbk/sbking/gui/frames/NetworkClientScreen.java, src/main/java/br/com/sbk/sbking/gui/painters/ConnectToServerPainter.java, src/main/java/br/com/sbk/sbking/networking/core/properties/FileProperties.java, src/main/java/br/com/sbk/sbking/networking/core/properties/NetworkingProperties.java, src/main/java/br/com/sbk/sbking/networking/server/LobbyServer.java, src/main/resources/config.dev.xml.example, src/main/resources/config.xml, src/main/resources/networkConfiguration.cfg, src/test/java/br/com/sbk/sbking/networking/core/properties/NetworkingPropertiesTest.java
=> Use only one Server

src/main/java/br/com/sbk/sbking/gui/frames/SBKingClientJFrame.java, src/main/java/br/com/sbk/sbking/gui/main/MainNetworkGame.java, src/main/java/br/com/sbk/sbking/gui/painters/ConnectToServerPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/PainterFactory.java, src/main/java/br/com/sbk/sbking/gui/screens/CagandoNoBequinhoScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/GameScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/KingScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/LobbyScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/MinibridgeScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/PositiveKingScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/SBKingScreen.java, src/main/java/br/com/sbk/sbking/gui/screens/WelcomeScreen.java
=> Lobby screen

src/main/java/br/com/sbk/sbking/gui/elements/ChooseGameModeOrStrainElement.java, src/main/java/br/com/sbk/sbking/gui/elements/ChoosePositiveOrNegativeElement.java, src/main/java/br/com/sbk/sbking/gui/elements/CreateTableElement.java, src/main/java/br/com/sbk/sbking/gui/elements/SBKingRadioButtonGroupCreator.java, src/main/java/br/com/sbk/sbking/gui/painters/LobbyScreenPainter.java, src/main/java/br/com/sbk/sbking/gui/screens/LobbyScreen.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetUtils.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/ClientToServer/CreateTableMessage.java
=> [feat] add table creation selection to LobbyScreen

src/main/java/br/com/sbk/sbking/dto/LobbyScreenTableDTO.java, src/test/java/br/com/sbk/sbking/dto/LobbyScreenTableDTOTest.java
=> [chore] create LobbyScreenTableDTO

src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/LobbyServer.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java
=> [feat] multiple tables

src/main/java/br/com/sbk/sbking/dto/LobbyScreenTableDTO.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetClientListenerFactory.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetUtils.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingClientMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingServerMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/ClientToServer/GetTablesMessage.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/ServerToClient/GetTablesResponseMessage.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java, src/test/java/br/com/sbk/sbking/dto/LobbyScreenTableDTOTest.java
How to test:
- run server
- run client
- connect client
- check that the table description appear at the LOG.
=> [feat] GetTablesMessage

src/main/java/br/com/sbk/sbking/core/CagandoNoBequinhoGame.java, src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/core/KingGame.java, src/main/java/br/com/sbk/sbking/core/MinibridgeGame.java, src/main/java/br/com/sbk/sbking/core/PositiveKingGame.java, src/main/java/br/com/sbk/sbking/core/Score.java, src/main/java/br/com/sbk/sbking/gui/JElements/ClaimButton.java, src/main/java/br/com/sbk/sbking/gui/elements/ClaimElement.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionWithDummyBoardElements.java, src/main/java/br/com/sbk/sbking/gui/listeners/ClientActionListener.java, src/main/java/br/com/sbk/sbking/gui/painters/DealPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/SpectatorPainter.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClientActionListener.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetUtils.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingServerMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/ClientToServer/ClaimMessage.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/GameServer.java, src/test/java/br/com/sbk/sbking/core/DealTest.java
=> [feat] claim

src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionWithDummyBoardElements.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/CagandoNoBequinhoGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/GameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/KingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/MinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameServer/PositiveKingGameServer.java, src/test/java/br/com/sbk/sbking/core/DealTest.java
=> [feat] show entire board at the end of the deal

src/test/java/br/com/sbk/sbking/dto/LobbyScreenTableDTOTest.java
Fix this issue: https://sonarcloud.io/organizations/rulojuka/issues?open=AXjmrR60lD9Orxsl9Btp&resolved=false&types=BUG
=> [fix] LobbyScreenTableDTOTest

src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoNoTrumpOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoNoTrumpOpeningBoardRuleTest.java
=> [feat] 2NT opening

src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoClubsOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoClubsOpeningBoardRuleTest.java
=> [feat] 2 clubs opening

src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMajorOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMajorOpeningBoardRuleTest.java
=> [feat] 1 Major opening

src/main/java/br/com/sbk/sbking/core/HandEvaluations.java, src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMinorOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/HandEvaluationsTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMinorOpeningBoardRuleTest.java
=> [feat] 1 Minor opening

src/main/java/br/com/sbk/sbking/core/HandEvaluations.java, src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasFourWeakOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/HandEvaluationsTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasFourWeakOpeningBoardRuleTest.java
=> [feat] 4 weak opening

src/main/java/br/com/sbk/sbking/core/HandEvaluations.java, src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoWeakOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/HandEvaluationsTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasTwoWeakOpeningBoardRuleTest.java
=> [feat] 2-weak

src/main/java/br/com/sbk/sbking/core/HandEvaluations.java, src/main/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasThreeWeakOpeningBoardRule.java, src/test/java/br/com/sbk/sbking/core/HandEvaluationsTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasFourWeakOpeningBoardRuleTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMajorOpeningBoardRuleTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasOneMinorOpeningBoardRuleTest.java, src/test/java/br/com/sbk/sbking/core/boardrules/bridgeopenings/DealerHasThreeWeakOpeningBoardRuleTest.java
=> [feat] 3 weak opening

src/main/java/br/com/sbk/sbking/gui/painters/PainterFactory.java, src/main/java/br/com/sbk/sbking/gui/painters/WaitingForChoosingGameModeOrStrainPainter.java
=> [chore] remove king score board from unwanted games

src/main/java/br/com/sbk/sbking/gui/elements/EssentialDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/painters/WaitingForChoosingGameModeOrStrainPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/WaitingForChoosingPositiveOrNegativePainter.java
=> [chore] remove gameElements from unwanted places

src/main/java/br/com/sbk/sbking/gui/elements/AllTableCardsElement.java
Arrumar alinhamento das mesas do lobby - mais ou menos onde tá o leave table
=> [fix] table alignment

src/main/java/br/com/sbk/sbking/core/Suit.java, src/main/java/br/com/sbk/sbking/gui/constants/FrameConstants.java, src/main/java/br/com/sbk/sbking/gui/elements/AllDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/EssentialDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/SpectatorsElement.java, src/main/java/br/com/sbk/sbking/gui/main/MainNetworkGame.java, src/main/java/br/com/sbk/sbking/gui/main/SpectatorNamesUpdater.java, src/main/java/br/com/sbk/sbking/gui/painters/DealPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/DealWithDummyPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/PainterFactory.java, src/main/java/br/com/sbk/sbking/gui/painters/SpectatorPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/WaitingForChoosingGameModeOrStrainPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/WaitingForChoosingPositiveOrNegativePainter.java, src/main/java/br/com/sbk/sbking/gui/screens/CagandoNoBequinhoScreen.java, src/main/java/br/com/sbk/sbking/networking/client/SBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingClient.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetUtils.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingClientMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/SBKingServerMessageConsumer.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/clienttoserver/GetTableSpectatorsMessage.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/servertoclient/GetTableSpectatorsResponseMessage.java, src/main/java/br/com/sbk/sbking/networking/server/SBKingServer.java, src/main/java/br/com/sbk/sbking/networking/server/Table.java
**Player screen**
**Spectator screen**
=> [feat] draw the spectators name on screen

src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/core/Trick.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionWithDummyBoardElements.java, src/main/java/br/com/sbk/sbking/gui/painters/DealWithDummyPainter.java, src/main/java/br/com/sbk/sbking/gui/painters/PainterFactory.java, src/test/java/br/com/sbk/sbking/core/TrickTest.java
This PR includes
- undo feature considering dummy player
- undo button don't appear to dummy
- show spectators element to minibridge screen
=> Undo for Minibridge

src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionWithDummyBoardElements.java
This PR includes:
- Claim don't appear to dummy
- Accept claim don't need dummy approval
- Correct accept and reject claim position
=> [feat] claim not visible for dummy

src/main/java/br/com/sbk/sbking/core/Deal.java, src/main/java/br/com/sbk/sbking/core/game/CagandoNoBequinhoGame.java, src/main/java/br/com/sbk/sbking/core/game/KingGame.java, src/main/java/br/com/sbk/sbking/core/game/MinibridgeGame.java, src/main/java/br/com/sbk/sbking/core/game/PositiveKingGame.java, src/main/java/br/com/sbk/sbking/core/game/TrickGame.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/KingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/MinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/PositiveKingGameServer.java
- When setting a ruleset
- When initializing the game
Closes #163
=> [fix] don't create new Deal in unnecessary places

src/main/java/br/com/sbk/sbking/gui/constants/FrameConstants.java, src/main/java/br/com/sbk/sbking/gui/elements/AllDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/EssentialDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/RulesetElement.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionBoardElements.java, src/main/java/br/com/sbk/sbking/gui/elements/SpecificDirectionWithDummyBoardElements.java
This PR includes:
- New design on RulesetElement to attend color-blinded users
- Update ClaimElement and RulesetElement positions
Closes #160
=> [feat] design for color blind-users and update element positions

src/main/java/br/com/sbk/sbking/core/game/CagandoNoBequinhoGame.java, src/main/java/br/com/sbk/sbking/core/game/KingGame.java, src/main/java/br/com/sbk/sbking/core/game/MinibridgeGame.java, src/main/java/br/com/sbk/sbking/core/game/PositiveKingGame.java, src/main/java/br/com/sbk/sbking/core/game/TrickGame.java, src/main/java/br/com/sbk/sbking/gui/elements/CreateTableElement.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameNameFromGameServerIdentifier.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameScreenFromGameNameIdentifier.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameServerFromGameNameIdentifier.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/CagandoNoBequinhoGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/KingGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/MiniMinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/MinibridgeGameServer.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/PositiveKingGameServer.java, src/test/java/br/com/sbk/sbking/core/game/CagandoNoBequinhoGameTest.java, src/test/java/br/com/sbk/sbking/core/game/KingGameTest.java, src/test/java/br/com/sbk/sbking/core/game/MinibridgeGameTest.java, src/test/java/br/com/sbk/sbking/core/game/PositiveKingGameTest.java
Also, use some inversion of control to pass responsibility of deck choosing to the gameServer instead of the game.
=> [feat] add mini-minibridge on a separate gameServer

src/main/java/br/com/sbk/sbking/core/boarddealer/Partial40CardDeck.java, src/main/java/br/com/sbk/sbking/gui/elements/CreateTableElement.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameNameFromGameServerIdentifier.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameScreenFromGameNameIdentifier.java, src/main/java/br/com/sbk/sbking/networking/kryonet/messages/GameServerFromGameNameIdentifier.java, src/main/java/br/com/sbk/sbking/networking/server/gameserver/TenCardsMinibridgeGameServer.java, src/test/java/br/com/sbk/sbking/core/boarddealer/Partial40CardDeckTest.java
Introduces the **TenCard-Minibridge** game, which is Minibridge but with a 40 card deck (ten cards for each player).
No tests added, I haven't looked at it yet, but I was able to launch some clients and successfully play a board of the game.
Let me know if you want me to eventually squash the commits! (:
=> Ten cards minibridge
